### ISSUE TITLE
Dataset preparation

### ISSUE THREAD

**Issue by jiaxiangc** [vgthengane/Continual-CLIP#1]
I want to know how prepare dataset.
Do I need to write new code?
Or just make the dataset directory file correct？
Can you tell me about the dataset directory of your example?

**Comment by zaiquanyang** [comment]
> I want to know how prepare dataset. Do I need to write new code? Or just make the dataset directory file correct？ Can you tell me about the dataset directory of your example?

Do you have solved the dataset preparation?

**Comment by haoranD** [comment]
Hi, guys.

I am also wondering how to prepare the data. Did you make it work?

Thanks a lot.

**Comment by vgthengane** [comment]
Data preparation is handled by the https://github.com/Continvvm/continuum library. To use this repository you just need to download the dataset and provide the path.
